# Generated by Django 5.1.6 on 2025-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
